
language: node_js

node_js: stable

branchs: 
    only: 
        - hexo

before_install: 
    - export TZ='Asia/Shanghai' 
    - openssl aes-256-cbc -K $encrypted_c53d3c040872_key -iv $encrypted_c53d3c040872_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent)
    - ssh-add ~/.ssh/id_rsa
    - cp ./.travis/ssh_config ~/.ssh/config
    - git config --global user.name "ytlm"
    - git config --global user.email "ytlm1314@gmail.com"

install: 
    - npm install hexo-cli -g
    - npm install

cache: 
    directories: 
        - node_modules

before_script: 
    - git clone https://github.com/iissnan/hexo-theme-next themes/next
    - cp themes/config/_config.yml themes/next/_config.yml
    - cp themes/images/* themes/next/source/images/
    - git clone --branch master https://github.com/ytlm/ytlm.github.io ./.deploy_git

script: 
    - hexo clean
    - hexo generate
    - hexo deploy --silent

notifications: 
    email: ytlm1314@gmail.com
    on_success: change
    on_failure: always
