language: node_js

node_js: stable

branchs:
    only:
        - hexo

before_install:
    - export TZ='Asia/Shanghai'
    - openssl aes-256-cbc -K $encrypted_c53d3c040872_key -iv $encrypted_c53d3c040872_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent)
    - ssh-add ~/.ssh/id_rsa
    - cp ./.travis/ssh_config ~/.ssh/config
    - git config --global user.name "ytlm"
    - git config --global user.email "ytlm1314@gmail.com"

install:
    - npm install hexo-cli -g
    - npm install

cache:
    directories:
        - node_modules

before_script:
    - git clone https://github.com/theme-next/hexo-theme-next.git themes/next --quiet
    - cp themes/config/_config.yml themes/next/_config.yml
    - git clone --branch master https://github.com/ytlm/ytlm.github.io ./.deploy_git --quiet

script:
    - hexo clean --silent
    - hexo generate --silent
    - hexo deploy --silent
    - bash ./script/post.sh

notifications:
    email: ytlm.lv@gmail.com
        on_success: change
        on_failure: always
    slack:
        on_success: always
        on_failure: always
        secure: jNLE9n+QmFTtSLUBM3nvcfE3Bb7bCzKV4Uq1DtK147W5BkAmg+e6dg6msPK9bdmQhj0RerAAz3Kk0ndjW+oRuaG7PvMxZVSHxO9+z27LsMn7S7zE84MVkoEiT0d2jVSyRLS6/a/IzEWiQIHUreBCXNxoAxMN+A6DM6tXy5QJgQvzXLR+KlJr1uXWodhOWAz1HIy9icus0K+bq6Dte8SYo5bJ8jib/npz5+fg1hiYv5qygVWcHaik7X4yZff/hmbtggweC9nFwkZW7GyCe+tOSPhgivT33oqOa/zhxKgOPuLoswAUO95DCYn5YblkcUcDVReTz0VikG61qXoPP4lsDEBaYUrH27kyX1cueCCQrn2Y/rHvNUyYTA13f41V2pS+421bFkAVFXVDsz/g/N0F+jOj0tSC24vq1zTwzIZqCPP90pCfxS41Lt/D+lB2xLG1pdsuqGwsV4zKJpv7K6r28TCBZLRQzH9kSFx5dpGDq+dcDFMvgUxyLeny5p1Toba736mPqE6Tx5mD8qHVSb05PmtEOSV8GevCPcvQSHJp+cLNprq6NpLw2haAliM0u6CwuMlDDGcBix70D5g2B4oFky4baPRv8QVJ/6Omy3U15CqyDHHdCURaj7a6Wephrgcv8AHRypSnAAfiCiryGNET0alPzwc7l6nsilNYotGss/M=
